update:
  ignore:
    - .git
    - .github/workflows
    - README.md
  force:
    - scripts/reports/cloc-repository.sh
    - scripts/reports/generate-sbom.sh
    - scripts/reports/perform-static-analysis.sh
    - scripts/reports/scan-vulnerabilities.sh

delete:
  - docs/adr/ADR-001_Use_git_hook_and_GitHub_action_to_check_the_editorconfig_compliance.md
  - docs/adr/ADR-002_Scan_repository_for_hardcoded_secrets.md
  - scripts/cloc-repository.sh
  - scripts/cve-scanner.sh
  - scripts/sbom-generator.sh

version:
  file: scripts/config/.repository-template.yaml
