rules:
  update:
    - scripts/reports/cloc-repository.sh
    - scripts/reports/generate-sbom.sh
    - scripts/reports/perform-static-analysis.sh
    - scripts/reports/scan-vulnerabilities.sh
  delete:
    - docs/adr/ADR-001_Use_git_hook_and_GitHub_action_to_check_the_editorconfig_compliance.md
    - docs/adr/ADR-002_Scan_repository_for_hardcoded_secrets.md
    - docs/adr/ADR-XXX_Agree_CICD_pipeline_structure.md
    - docs/diagrams/Repository_Template_GitHub_Generic.png
    - docs/diagrams/Repository_Template.drawio
    - scripts/githooks/.pre-commit-config.yaml
    - scripts/githooks/markdown-pre-commit.sh
    - scripts/githooks/secret-scan-pre-commit.sh
    - scripts/test/unit
    - scripts/cloc-repository.sh
    - scripts/cve-scanner.sh
    - scripts/sbom-generator.sh
  ignore:
    - docs/adr/ADR-001_Use_git_hook_and_GitHub_action_to_check_the_editorconfig_compliance.md
    - docs/adr/ADR-002_Scan_repository_for_hardcoded_secrets.md
    - docs/adr/ADR-XXX_Agree_CICD_pipeline_structure.md
    - docs/diagrams/CD_Pipeline_Structure.drawio
    - docs/diagrams/CD_Pipeline_Structure.png
    - docs/diagrams/Repository_Template_GitHub_Generic.png
    - docs/diagrams/Repository_Template.drawio
    - project.code-workspace
    - README.md
    - TODO.md
    - VERSION
    # # Changes to these files need to be managed by a script
    # - .gitignore
    # - .tool-versions
    # - Makefile
scripts:
  # TODO: Run scripts listed here on the destination repository
