name: "Synchronise Template"
description: "Synchronise repository with the template"
inputs:
  name:
    description: "Name to print"
    required: true
outputs:
  time:
    description: "The time name was printed"
runs:
  using: "docker"
  image: ./docker/Dockerfile
  args:
    - ${{ inputs.name }}
