name: "Update From Template Action"
description: "Update repository from the template repository"
inputs:
  dir1:
    description: "dir1"
    required: true
  dir2:
    description: "dir2"
    required: true
runs:
  using: "docker"
  image: ./Dockerfile
  args:
    - ${{ inputs.dir1 }}
    - ${{ inputs.dir2 }}
