name: "Update From Template Action"
description: "Update repository from the template repository"
inputs:
  build_datetime:
    description: "Build datetime, set by the CI/CD pipeline workflow"
    required: true
  repository_template:
    description: "Repository template"
    required: true
  repository_to_update:
    description: "Repository to update"
    required: true
  git_user_name:
    description: "Committer git user.name"
    required: true
  git_user_email:
    description: "Committer git user.email"
    required: true
  gh_app_id:
    description: "GitHub App ID"
    required: true
  gh_app_pk:
    description: "GitHub App private key"
    required: true
runs:
  using: "docker"
  image: ./Dockerfile.effective
  env:
    BUILD_DATETIME: ${{ inputs.build_datetime }}
    REPOSITORY_TEMPLATE: ${{ inputs.repository_template }}
    REPOSITORY_TO_UPDATE: ${{ inputs.repository_to_update }}
    GIT_USER_NAME: ${{ inputs.git_user_name }}
    GIT_USER_EMAIL: ${{ inputs.git_user_email }}
    GH_APP_ID: ${{ inputs.gh_app_id }}
    GH_APP_PK: ${{ inputs.gh_app_pk }}
