name: "Synchronise Template"
description: "Synchronise repository with the template"
inputs:
  message:
    description: "Message to print"
    required: true
outputs:
  time:
    description: "The time message was printed"
runs:
  using: "docker"
  image: ./docker/Dockerfile
  args:
    - ${{ inputs.who-to-greet }}
