name: "Synchronise Template"
description: "Synchronise repository with the template"
inputs:
  dir1:
    description: "dir1"
    required: true
  dir2:
    description: "dir2"
    required: true
# outputs:
#   time:
#     description: "The time name was printed"
runs:
  using: "docker"
  image: ./build/docker/Dockerfile
  args:
    - /compare-directories
    - --dir1=${{ inputs.dir1 }}
    - --dir2=${{ inputs.dir2 }}
