name: "Update From Template Action"
description: "Update repository from the template repository"
inputs:
  build_datetime:
    description: "Build datetime, set by the CI/CD pipeline workflow"
    required: true
  repository_template:
    description: "Repository template"
    required: true
  repository_to_update:
    description: "Repository to update"
    required: true
  git_user_name:
    description: "Committer git user.name"
    required: true
  git_user_email:
    description: "Committer git user.email"
    required: true
  github_app_id:
    description: "GitHub App ID"
    required: true
  github_app_private_key_content:
    description: "GitHub App private key content"
    required: true
  github_app_commit_signing_key_id:
    description: "GitHub App commit signing key id"
    required: true
  github_app_commit_signing_key_content:
    description: "GitHub App commit signing key content"
    required: true
  github_app_commit_signing_key_passphrase:
    description: "GitHub App commit signing key passphrase"
    required: true
runs:
  using: "docker"
  image: ./Dockerfile.effective
  env:
    BUILD_DATETIME: ${{ inputs.build_datetime }}
    REPOSITORY_TEMPLATE: ${{ inputs.repository_template }}
    REPOSITORY_TO_UPDATE: ${{ inputs.repository_to_update }}
    GIT_USER_NAME: ${{ inputs.git_user_name }}
    GIT_USER_EMAIL: ${{ inputs.git_user_email }}
    GITHUB_APP_ID: ${{ inputs.github_app_id }}
    GITHUB_APP_PK_CONTENT: ${{ inputs.github_app_private_key_content }}
    GITHUB_APP_SK_ID: ${{ inputs.github_app_commit_signing_key_id }}
    GITHUB_APP_SK_CONTENT: ${{ inputs.github_app_commit_signing_key_content }}
    GITHUB_APP_SK_PASSPHRASE: ${{ inputs.github_app_commit_signing_key_passphrase }}
