name: "Update From Template Action"
description: "Update repository from the template repository"
inputs:
  build_datetime_local:
    description: "Build datetime local, set by the CI/CD pipeline workflow"
    required: true
  build_datetime:
    description: "Build datetime, set by the CI/CD pipeline workflow"
    required: true
  build_timestamp:
    description: "Build timestamp, set by the CI/CD pipeline workflow"
    required: true
  source_dir:
    description: "Source directory"
    required: true
  destination_dir:
    description: "Destination directory"
    required: true
  git_user_name:
    description: "Committer git user.name"
    required: true
  git_user_email:
    description: "Committer git user.email"
    required: true
  github_token:
    description: "GitHub App token"
    required: true
runs:
  using: "docker"
  image: ./Dockerfile.effective
  env:
    BUILD_DATETIME_LOCAL: ${{ inputs.build_datetime_local }}
    BUILD_DATETIME: ${{ inputs.build_datetime }}
    BUILD_TIMESTAMP: ${{ inputs.build_timestamp }}
    SOURCE_DIR: ${{ inputs.source_dir }}
    DESTINATION_DIR: ${{ inputs.destination_dir }}
    GIT_USER_NAME: ${{ inputs.git_user_name }}
    GIT_USER_EMAIL: ${{ inputs.git_user_email }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
