name: "Update From Template Action"
description: "Update repository from the template repository"
inputs:
  source-dir:
    description: "Source directory"
    required: true
  destination-dir:
    description: "Destination directory"
    required: true
runs:
  using: "docker"
  image: ./Dockerfile
  args:
    - ${{ inputs.source-dir }}
    - ${{ inputs.destination-dir }}
