rules:
  copy: # These files cannot be ignored by user configuration
    - path/to/file
  delete:
    - legacy/file
  ignore:
    - custom/file

version:
  file: scripts/config/.repository-template.yaml
