name: "Perform static analysis"
description: "Perform static analysis"
inputs:
  sonar_token:
    description: "Sonar token API key"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Check prerequisites for performing static analysis"
      shell: bash
      id: check
      run: echo "secret_exist=${{ inputs.sonar_token != '' }}" >> $GITHUB_OUTPUT
    - name: "Perform static analysis"
      shell: bash
      if: steps.check.outputs.secret_exist == 'true'
      run: |
        export SONAR_TOKEN=${{ inputs.sonar_token }}
        ./scripts/reports/perform-static-analysis.sh
