name: Test Stage

on:
  workflow_call:
    inputs:
      build_datetime:
        description: "Build datetime, set by the CI/CD pipeline workflow"
        required: true
        type: string
      golang_version:
        description: "Go version, set by the CI/CD pipeline workflow"
        required: true
        type: string
    secrets:
      UPDATE_FROM_TEMPLATE_GH_APP_ID:
        description: "GitHub App ID"
        required: true
      UPDATE_FROM_TEMPLATE_GH_APP_PK_CONTENT:
        description: "GitHub App private key content"
        required: true
      UPDATE_FROM_TEMPLATE_GH_APP_SK_ID:
        description: "GitHub App commit signing key ID"
        required: true
      UPDATE_FROM_TEMPLATE_GH_APP_SK_CONTENT:
        description: "GitHub App commit signing key content"
        required: true
      UPDATE_FROM_TEMPLATE_GH_APP_SK_PASSPHRASE:
        description: "GitHub App commit signing key passphrase"
        required: true

jobs:
  # cmd-unit-test:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version: ${{ inputs.golang_version }}
  #     - name: Run unit test
  #       run: |
  #         make cmd-unit-test
  # cmd-contract-test:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version: ${{ inputs.golang_version }}
  #     - name: Run contract test
  #       run: |
  #         make cmd-contract-test DATASET=large
  action-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: "Run action test"
        uses: ./tests
        with:
          build_datetime: ${{ inputs.build_datetime }}
          github_app_id: "${{ secrets.UPDATE_FROM_TEMPLATE_GH_APP_ID }}"
          github_app_private_key_content: "${{ secrets.UPDATE_FROM_TEMPLATE_GH_APP_PK_CONTENT }}"
          github_app_commit_signing_key_id: "${{ secrets.UPDATE_FROM_TEMPLATE_GH_APP_SK_ID }}"
          github_app_commit_signing_key_content: "${{ secrets.UPDATE_FROM_TEMPLATE_GH_APP_SK_CONTENT }}"
          github_app_commit_signing_key_passphrase: "${{ secrets.UPDATE_FROM_TEMPLATE_GH_APP_SK_PASSPHRASE }}"
