name: Commit Stage

on:
  workflow_call:
    inputs:
      build_datetime:
        description: "Build datetime, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_timestamp:
        description: "Build timestamp, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_epoch:
        description: "Build epoch, set by the CI/CD pipeline workflow"
        required: true
        type: string
      version:
        description: "Version of the software, set by the CI/CD pipeline workflow"
        required: true
        type: string

jobs:
  scan-secrets:
    uses: ./.github/workflows/job-scan-secrets.yaml
  check-file-format:
    uses: ./.github/workflows/job-check-file-format.yaml
  check-markdown-format:
    uses: ./.github/workflows/job-check-markdown-format.yaml
  cloc-repository:
    uses: ./.github/workflows/job-cloc-repository.yaml
  scan-dependencies:
    uses: ./.github/workflows/job-scan-dependencies.yaml
