name: Test Stage

on:
  workflow_call:
    inputs:
      build_datetime_local:
        description: "Build datetime local, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_datetime:
        description: "Build datetime, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_timestamp:
        description: "Build timestamp, set by the CI/CD pipeline workflow"
        required: true
        type: string
      golang_version:
        description: "Go version, set by the CI/CD pipeline workflow"
        required: true
        type: string
    secrets:
      UPDATE_FROM_TEMPLATE_GH_APP_ID:
        description: "GitHub App ID passed from the caller workflow"
        required: true
      UPDATE_FROM_TEMPLATE_GH_APP_PK:
        description: "GitHub App private key passed from the caller workflow"
        required: true
jobs:
  # cmd-unit-test:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version: ${{ inputs.golang_version }}
  #     - name: Run unit test
  #       run: |
  #         make cmd-unit-test
  # cmd-contract-test:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version: ${{ inputs.golang_version }}
  #     - name: Run contract test
  #       run: |
  #         make cmd-contract-test DATASET=large
  action-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: "Run action test"
        uses: ./tests
        with:
          build_datetime_local: ${{ inputs.build_datetime_local }}
          build_datetime: ${{ inputs.build_datetime }}
          build_timestamp: ${{ inputs.build_timestamp }}
          gh_app_id: "${{ secrets.UPDATE_FROM_TEMPLATE_GH_APP_ID }}"
          gh_app_pk: "${{ secrets.UPDATE_FROM_TEMPLATE_GH_APP_PK }}"
